name: luad-survival
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - pyyaml
  - tqdm
  - jupyter
  - ipykernel
  - requests
  - pip:
      - lifelines
      - rich